# Generated by Django 4.2.7 on 2025-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymentmethod_mobilemoneytransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemoneytransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
