# Generated by Django 4.2.7 on 2025-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_customerprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
